### ISSUE TITLE
Library fails to compile under Xcode 11.4b1

### ISSUE THREAD

**Issue by piercifani** [pointfreeco/swift-snapshot-testing#295]
When integrating this great library into our project using SPM, the project fails to compile under the latest beta of Xcode. Maybe this is a bug within the beta, maybe it's a new issue being exposed now:

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/869981/73956456-45a00300-4905-11ea-9492-ee9075489771.png">

Removing SnapshotTesting from the project fixes this compilation issue (but can't really unit test anything now xD)

Let me know if you need anything specific to reproduce this issue

**Comment by stephencelis** [comment]
This was fixed on master but we've done a 1.7.2 point release that you can upgrade to!

**Comment by piercifani** [comment]
Thanks a lot Stephen!

**Comment by piercifani** [comment]
Hey Stephen!

I'm still seeing this issue when compiling with Xcode 11.4b1. Let me explain what the project looks like:

- We have `FooKit` as a shared library where Foundation code of the app goes. This has `swift-snapshot-testing` to test `NSURLRequest`s sent. This library is packaged in as Swift Package.

- Then there's `Foo.app` which links `FooKit` and also has a unit test bundle where `swift-snapshot-testing` is linked as well. All dependencies are managed using SPM.

Compiling works fine and also unit testing the `FooKit` package. The error linked above is only present when running unit tests for the whole project.

I honestly don't know if this is an error on SPM or on `swift-snapshot-testing ` since I've checked your `Package.swift` and it doesn't look like anything fancy is going on there that might cause this.

Please let me know if there's anything I can do to help you guys with this error.

**Comment by stephencelis** [comment]
Hi @piercifani! You've definitely updated to 1.7.2? This is definitely a regression and probably a bug with Swift 5.2 and/or SPM, we're just trying to provide a fix. If you're on 1.7.2 I wonder if you could figure out and provide a minimum viable repro?

**Comment by piercifani** [comment]
I can't seem to reproduce in a smaller repo, so I'm trying to figure out if something else is off in my setup. I'll update in this same issue if I can do it.

Thanks for your time!
