### ISSUE TITLE
Snapshot taken on CI has slight color differences compared to local

### ISSUE THREAD

**Issue by edulpn** [pointfreeco/swift-snapshot-testing#313]
Hi everybody, I'm having an issue here with color discrepancies in an image view. I'm using KIF framework for UI Tests and SnapshotTesting to take screenshots between interactions (asserts made on the app key window). Everything works fine, except that I get color differences from snapshots taken on my local machine vs snapshots taken on CI machine (both running the same stack, Mojave + Xcode 11.3).

Some examples below:

This one is taken by CI machine
![asdf](https://user-images.githubusercontent.com/4682317/76860292-8874c500-6839-11ea-99fe-2d1dfbf78a44.png)

This one is taken by my local computer
![testOpenAndClose 1](https://user-images.githubusercontent.com/4682317/76860385-b3f7af80-6839-11ea-8b70-d81673b9db6a.png)

This is the comparison of both images made by `imagemagick`
![result](https://user-images.githubusercontent.com/4682317/76860409-bd811780-6839-11ea-800e-016193cf0914.png)

And these are the color discrepancies of a same pixel, measured  by macOS `Digital Color Meter`
![WhatsApp Image 2020-03-17 at 10 11 38](https://user-images.githubusercontent.com/4682317/76860529-f28d6a00-6839-11ea-9998-6f726c784f7d.jpeg)
![WhatsApp Image 2020-03-17 at 10 11 22](https://user-images.githubusercontent.com/4682317/76860552-f7eab480-6839-11ea-9c7f-87e3a9a46014.jpeg)

I know there are lots of variables and also using KIF, but do you guys have any idea of what might be wrong?

Thanks!

**Comment by iandundas** [comment]
Just to chime in that we're seeing the same issue. When run our snapshot tests from fastlane, **assets** (pngs etc) seem to be slightly differently rendered compared when we launch the same tests on the same machine, same simulator, from Xcode. Very strange.

![CleanShot 2020-04-05 at 10 16 09](https://user-images.githubusercontent.com/1131967/78470039-84e0a980-7726-11ea-88b6-4624932d23ed.gif)

**Comment by gobetti** [comment]
I'm not seeing any difference between fastlane and Xcode on my machine so far, but I do also experience tiny nuances between my machine's and CI's snapshots, specifically on iOS 13. Having a non-zero corner radius in a native view is enough to have a difference, don't really need to involve assets.

**Comment by aegzorz** [comment]
We're seeing similar results between different machines, as soon as we add "real life" images we get a small imperceptible differences causing the test to fail.

**Comment by gobetti** [comment]
@aegzorz could you please check if your differences are only on iOS 13? And how much is the difference? (i.e. what's the RGB for the different pixel in the two different runs)

**Comment by aegzorz** [comment]
We're only testing on iOS 13 currently. Seems using shadows on views throws it off sometimes as well. Haven't done any RGB measurements yet.

**Comment by gobetti** [comment]
sadly, lowering the precision or considering as "equal" pixels with an invisible difference aren't performant solutions. Tests that don't pass the `memcmp` comparison are orders of magnitude slower so having to go through the bytes comparison loop is probably very undesirable.

**Comment by stephencelis** [comment]
We have this in our README:

> ⚠️ Warning: Snapshots must be compared using a simulator with the same OS, device gamut, and scale as the simulator that originally took the reference to avoid discrepancies between images.

Is it possible to ensure that CI and developer machines test in a consistent environment?

**Comment by iandundas** [comment]
Could be something there, but we were seeing it on the exact same simulator (model, OS etc) on the same machine, with the difference being only between running the tests from Xcode vs running them (locally) from fastlane

**Comment by stephencelis** [comment]
Huh. Perhaps someone with fastlane experience can explain? Maybe it's worth opening an issue with them to ask?

**Comment by iandundas** [comment]
Good idea, will do 👍🏻

**Comment by iandundas** [comment]
I was just about to, when I realised above that some people are saying it is not fastlane which is causing this issue for them (but simply running the tests on a different machine). So a bit hesitant now to open that fastlane issue 🤔.

**Comment by gscalzo** [comment]
@iandundas it could be related to https://github.com/pointfreeco/swift-snapshot-testing/pull/288

**Comment by Nikoloutsos** [comment]
For future readers I faced this issue with different colours on different machines.
It happened when I tried to solve another problem with masked corner radius. For solving it I have to add host application to test module and enable a parameter called `DrawOnViewHierarchy` in .image strategy.
I removed them and then I recorded the snapshots tests for iPhone 8 14.4.
Then I forced fast lane to run tests on this simulator on CI and everything works great with 100% precision!

**Comment by AlexApriamashvili** [comment]
Hi guys,

I'm curious if there are any other solutions to this problem rather than hosting the test bundle inside the app executable? Unfortunately, this doesn't work in my case.

I've been looking into this problem for some time and here are my thoughts:

My understanding might not be completely correct, but I think that this problem might occur due to the fact that some CI (mostly cloud) runners would not have any graphic modules at all, so the entire rendering would have to happen on the CPU, versus GPU that is used when we are running tests via Xcode (>= v11.0). I also know that there is a difference in how rendering works for the simulators that run in the headless mode vs the ones that we see on screen. So even if the simulated device (and the machine is the same), there is still a high chance of running into this issue, while simply launching tests in different ways.

I've confirmed this on my local machine by recording snapshots via `xcodebuild` and then verifying those by running the tests from Xcode and vice versa. In both cases, there were insignificant differences between the reference and the result images which urged tests to fail, given that precision was intact.

I have a suspicion that reference images recorded via the `fastlane` (same `xcodebuild`) would have a better chance of matching the results received on CI. However, the developer experience from having to use `xcodebuild` to record the reference images would be worse than just using Xcode, I also reckon that there is still quite a high chance for those tests to be flaky.

Another observation that I've made is that in most of the cases the difference was in how assets (icons, images, etc) are being rendered, as the rest of the components were quite identical. I'm curious if anyone has explored how the use of different `UIImage.RenderingMode` and `UIGraphicsRendererFormat` could affect the result of running snapshot tests?

I would be keen on having a discussion on this matter here

**Comment by bill-florio** [comment]
It is still an issue for Xcode 13.3.1 (iOS 15.4 simulator). In my case reference image is created on M1 mac, Github action generated sightly different images.

**Comment by ejensen** [comment]
https://github.com/pointfreeco/swift-snapshot-testing/pull/628 should resolve this issue with a new perceptual difference calculation. A `perceptualPrecsion` value of [>=98% will prevent imperceivable differences](http://zschuessler.github.io/DeltaE/learn/#toc-defining-delta-e) from failing assertions while noticeable differences are still caught.

**Comment by KingOfBrian** [comment]
We have this same issue where one of our 6 CI machines fails 1-6 snapshots of our 500ish snapshots. We just changed everything to pass in `perceptualPrecision: 0.98` and we're still seeing the issue.

Here's the difference that shows up in Xcode:
![difference_3_FD4AAF4D-CE3A-4368-AEFD-9E873B5258D5](https://user-images.githubusercontent.com/114322/192366009-e645bcef-82e9-4923-aaf8-b11d9453bd94.png)

The wild thing is all these machines are setup via script and I don't understand how they could be different. The color profile angle sounded nice, but we don't have any `~/Library/ColorSync` directory. Looking at the color profiles via image magic shows `8-bit sRGB` for everything so it seems like it's the same.

**Comment by ejensen** [comment]
> We have this same issue where one of our 6 CI machines fails 1-6 snapshots of our 500ish snapshots. We just changed everything to pass in `perceptualPrecision: 0.98` and we're still seeing the issue.
> 
> The wild thing is all these machines are setup via script and I don't understand how they could be different. The color profile angle sounded nice, but we don't have any `~/Library/ColorSync` directory. Looking at the color profiles via image magic shows `8-bit sRGB` for everything so it seems like it's the same.

I found some cases where some machines, particularly virtualized environments, where the snapshot images are taken in a different color space than when the same test is run on a different machine with the exact same OS/simulator.
I put together https://github.com/pointfreeco/swift-snapshot-testing/pull/665 which attempts to normalize both the reference and new snapshot image's color space before comparison.
